#pragma once
// Hue-cycling background via pre-generated hue-ring textures, background
// continuous (DESIGN_EFFECTS.md §6.2.8). The actual rotated images are
// generated by platform::HueRingBuilder (win32, §6.2.8.1); this effect only
// picks which two ring indices to blend between each frame -- it never
// touches pixels itself.

#include "../EffectParams.h"
#include "../IEffect.h"

namespace core::fx {

struct HueRingSelection {
    int indexA = 0;
    int indexB = 1;
    float blendB = 0.0f; // 0 = pure indexA, 1 = pure indexB
};

// Pure: which two ring indices (out of `steps`) to blend at hue angle h
// degrees, and by how much.
HueRingSelection SelectHueRings(float hueDegrees, int steps);

class HueShiftEffect : public IEffect {
public:
    EffectId Id() const override { return EffectId::HueShift; }
    EffectKind Kind() const override { return EffectKind::Continuous; }
    GeometryKind Geometry() const override { return GeometryKind::Transform; }
    ExitStrategy Exit() const override { return ExitStrategy::Crossfade; }

    void Begin(const EffectContext& ctx) override;
    void Step(EffectFrame& frame) override;
    bool IsFinished() const override { return false; }

private:
    HueShiftParams params_;
};

} // namespace core::fx
